本番環境部分のコメントアウトを解除及びSlack通知チャンネルの変更

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -239,275 +239,199 @@ jobs:
           channel: ${SLACK_CHANNEL_ID_DEV}
           template: basic_success_1
 
-  # build-and-push-image:
-  #   docker:
-  #     - image: cimg/base:stable
-  #   steps:
-  #     - checkout
-  #     - run:
-  #         name: Checkout submodules
-  #         command: |
-  #           git submodule sync
-  #           git submodule update --init --recursive
+  build-and-push-image:
+    docker:
+      - image: cimg/base:stable
+    steps:
+      - checkout
+      - run:
+          name: Checkout submodules
+          command: |
+            git submodule sync
+            git submodule update --init --recursive
 
-  #     - setup_remote_docker
+      - setup_remote_docker
 
-  #     - aws-cli/setup
+      - aws-cli/setup
 
-  #     - run:
-  #         name: Configure AWS default region
-  #         command: |
-  #           if [ -z "$AWS_DEFAULT_REGION" ]; then
-  #             echo "AWS_DEFAULT_REGION is not set. Exiting."
-  #             exit 1
-  #           fi
-  #           aws configure set default.region $AWS_DEFAULT_REGION --profile default
+      - run:
+          name: Configure AWS default region
+          command: |
+            if [ -z "$AWS_DEFAULT_REGION" ]; then
+              echo "AWS_DEFAULT_REGION is not set. Exiting."
+              exit 1
+            fi
+            aws configure set default.region $AWS_DEFAULT_REGION --profile default
 
-  #     - run:
-  #         name: Get RDS endpoint and prepare .env.production
-  #         command: |
-  #           DB_HOST=$(aws rds describe-db-instances --db-instance-identifier ofcrm-mysql --query "DBInstances[0].Endpoint.Address" --output text)
+      - run:
+          name: Get RDS endpoint and prepare .env.production
+          command: |
+            DB_HOST=$(aws rds describe-db-instances --db-instance-identifier ofcrm-mysql --query "DBInstances[0].Endpoint.Address" --output text)
 
-  #           cd ./api/src
-  #           echo "APP_NAME=OFCRM" > .env.production
-  #           echo "APP_ENV=production" >> .env.production
-  #           echo "APP_KEY=${APP_KEY}" >> .env.production
-  #           echo "APP_DEBUG=false" >> .env.production
-  #           echo "APP_URL=https://api.tkb-tech.com" >> .env.production
-  #           echo "LOG_LEVEL=debug" >> .env.production
+            cd ./api/src
+            echo "APP_NAME=OFCRM" > .env.production
+            echo "APP_ENV=production" >> .env.production
+            echo "APP_KEY=${APP_KEY}" >> .env.production
+            echo "APP_DEBUG=false" >> .env.production
+            echo "APP_URL=https://api.tkb-tech.com" >> .env.production
+            echo "LOG_LEVEL=debug" >> .env.production
 
-  #           echo "DB_CONNECTION=mysql" >> .env.production
-  #           echo "DB_HOST=${DB_HOST}" >> .env.production
-  #           echo "DB_PORT=3306" >> .env.production
-  #           echo "DB_DATABASE=flowercrm_production" >> .env.production
-  #           echo "DB_USERNAME=${DB_USERNAME}" >> .env.production
-  #           echo "DB_PASSWORD=${DB_PASSWORD}" >> .env.production
+            echo "DB_CONNECTION=mysql" >> .env.production
+            echo "DB_HOST=${DB_HOST}" >> .env.production
+            echo "DB_PORT=3306" >> .env.production
+            echo "DB_DATABASE=flowercrm_production" >> .env.production
+            echo "DB_USERNAME=${DB_USERNAME}" >> .env.production
+            echo "DB_PASSWORD=${DB_PASSWORD}" >> .env.production
 
-  #           echo "BROADCAST_DRIVER=log" >> .env.production
-  #           echo "PUSHER_APP_ID=null" >> .env.production
-  #           echo "PUSHER_APP_KEY=null" >> .env.production
-  #           echo "PUSHER_APP_SECRET=null" >> .env.production
-  #           echo "PUSHER_HOST=null" >> .env.production
-  #           echo "PUSHER_PORT=null" >> .env.production
-  #           echo "PUSHER_SCHEME=https" >> .env.production
-  #           echo "PUSHER_APP_CLUSTER=null" >> .env.production
-  #           echo "LARAVEL_WEBSOCKETS_ENABLED=false" >> .env.production
+            echo "BROADCAST_DRIVER=log" >> .env.production
+            echo "PUSHER_APP_ID=null" >> .env.production
+            echo "PUSHER_APP_KEY=null" >> .env.production
+            echo "PUSHER_APP_SECRET=null" >> .env.production
+            echo "PUSHER_HOST=null" >> .env.production
+            echo "PUSHER_PORT=null" >> .env.production
+            echo "PUSHER_SCHEME=https" >> .env.production
+            echo "PUSHER_APP_CLUSTER=null" >> .env.production
+            echo "LARAVEL_WEBSOCKETS_ENABLED=false" >> .env.production
 
-  #           echo "JWT_SECRET=${JWT_SECRET}" >> .env.production
-  #           echo "JWT_ALGO=${JWT_ALGO}" >> .env.production
+            echo "JWT_SECRET=${JWT_SECRET}" >> .env.production
+            echo "JWT_ALGO=${JWT_ALGO}" >> .env.production
 
-  #           echo "FRONTEND_URL=https://front.tkb-tech.com" >> .env.production
+            echo "FRONTEND_URL=https://front.tkb-tech.com" >> .env.production
 
-  #     - restore_cache:
-  #         keys:
-  #           - docker-{{ .Branch }}-{{ checksum "./api/infra/php/Dockerfile.prod" }}
+      - restore_cache:
+          keys:
+            - docker-{{ .Branch }}-{{ checksum "./api/infra/php/Dockerfile.prod" }}
 
-  #     - run:
-  #         name: Set ECR URL and Build Docker Image
-  #         command: |
-  #           echo "Setting ECR URL..."
-  #           ECR_ENDPOINT=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
-  #           echo "export ECR_ENDPOINT=$ECR_ENDPOINT" >> $BASH_ENV
-  #           source $BASH_ENV
-  #           echo "ECR Endpoint: $ECR_ENDPOINT"
+      - run:
+          name: Set ECR URL and Build Docker Image
+          command: |
+            echo "Setting ECR URL..."
+            ECR_ENDPOINT=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
+            echo "export ECR_ENDPOINT=$ECR_ENDPOINT" >> $BASH_ENV
+            source $BASH_ENV
+            echo "ECR Endpoint: $ECR_ENDPOINT"
 
-  #           echo "Logging in to AWS ECR..."
-  #           aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_ENDPOINT
+            echo "Logging in to AWS ECR..."
+            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_ENDPOINT
 
-  #           echo "Building Docker image..."
-  #           docker build \
-  #             --build-arg NGINX_CONF_PATH=./infra/nginx/nginx.prod.conf \
-  #             --build-arg DEFAULT_CONF_PATH=./infra/nginx/default.prod.conf \
-  #             --build-arg PHP_INI_PATH=./infra/php/php.prod.ini \
-  #             --build-arg ENTRYPOINT_SCRIPT_PATH=./infra/php/docker-entrypoint.prod.sh \
-#             -t $ECR_ENDPOINT/ofcrm-app:${CIRCLE_SHA1} \
-#             -f ./api/infra/php/Dockerfile.prod \
-#             ./api
+            echo "Building Docker image..."
+            docker build \
+              --build-arg NGINX_CONF_PATH=./infra/nginx/nginx.prod.conf \
+              --build-arg DEFAULT_CONF_PATH=./infra/nginx/default.prod.conf \
+              --build-arg PHP_INI_PATH=./infra/php/php.prod.ini \
+              --build-arg ENTRYPOINT_SCRIPT_PATH=./infra/php/docker-entrypoint.prod.sh \
+              -t $ECR_ENDPOINT/ofcrm-app:${CIRCLE_SHA1} \
+              -f ./api/infra/php/Dockerfile.prod \
+              ./api
 
-#           if [ $? -ne 0 ]; then
-#             echo "Docker build failed"
-#             exit 1
-#           fi
+            if [ $? -ne 0 ]; then
+              echo "Docker build failed"
+              exit 1
+            fi
 
-#           echo "Docker build successful. Listing images:"
-#           docker images
+            echo "Docker build successful. Listing images:"
+            docker images
 
-#           echo "Pushing image to ECR..."
-#           docker push $ECR_ENDPOINT/ofcrm-app:${CIRCLE_SHA1}
+            echo "Pushing image to ECR..."
+            docker push $ECR_ENDPOINT/ofcrm-app:${CIRCLE_SHA1}
 
-#           if [ $? -ne 0 ]; then
-#             echo "Failed to push image to ECR"
-#             exit 1
-#           fi
+            if [ $? -ne 0 ]; then
+              echo "Failed to push image to ECR"
+              exit 1
+            fi
 
-#           echo "Image successfully pushed to ECR"
+            echo "Image successfully pushed to ECR"
 
-#           echo "Describing image in ECR..."
-#           aws ecr describe-images --repository-name ofcrm-app --image-ids imageTag=${CIRCLE_SHA1}
+            echo "Describing image in ECR..."
+            aws ecr describe-images --repository-name ofcrm-app --image-ids imageTag=${CIRCLE_SHA1}
 
-#     - save_cache:
-#         paths:
-#           - /home/circleci/.docker
-#         key: docker-{{ .Branch }}-{{ checksum "./api/infra/php/Dockerfile.prod" }}
+      - save_cache:
+          paths:
+            - /home/circleci/.docker
+          key: docker-{{ .Branch }}-{{ checksum "./api/infra/php/Dockerfile.prod" }}
 
-#     - run:
-#         name: Update ECS task definition
-#         command: |
-#           TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition ofcrm-app --query taskDefinition)
+- run:
+          name: Update ECS task definition
+          command: |
+            TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition ofcrm-app --query taskDefinition)
 
-#           NEW_TASK_DEFINITION=$(echo $TASK_DEFINITION | jq '{
-#             family: .family,
-#             taskRoleArn: .taskRoleArn,
-#             executionRoleArn: .executionRoleArn,
-#             networkMode: .networkMode,
-#             containerDefinitions: [.containerDefinitions[0] | .image = "'$ECR_ENDPOINT'/ofcrm-app:'${CIRCLE_SHA1}'"],
-#             volumes: .volumes,
-#             placementConstraints: .placementConstraints,
-#             requiresCompatibilities: .requiresCompatibilities,
-#             cpu: .cpu,
-#             memory: .memory
-#           }')
+            NEW_TASK_DEFINITION=$(echo $TASK_DEFINITION | jq '{
+              family: .family,
+              taskRoleArn: .taskRoleArn,
+              executionRoleArn: .executionRoleArn,
+              networkMode: .networkMode,
+              containerDefinitions: [.containerDefinitions[0] | .image = "'$ECR_ENDPOINT'/ofcrm-app:'${CIRCLE_SHA1}'"],
+              volumes: .volumes,
+              placementConstraints: .placementConstraints,
+              requiresCompatibilities: .requiresCompatibilities,
+              cpu: .cpu,
+              memory: .memory
+            }')
 
-#           NEW_TASK_INFO=$(aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEFINITION")
+            NEW_TASK_INFO=$(aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEFINITION")
 
-#           NEW_REVISION=$(echo $NEW_TASK_INFO | jq '.taskDefinition.revision')
-#           echo "New task definition revision: $NEW_REVISION"
+            NEW_REVISION=$(echo $NEW_TASK_INFO | jq '.taskDefinition.revision')
+            echo "New task definition revision: $NEW_REVISION"
 
-#     - run:
-#         name: Set job status
-#         command: |
-#           echo 'export CCI_STATUS="${CIRCLE_JOB}"' >> $BASH_ENV
-#           source $BASH_ENV
+      - run:
+          name: Set job status
+          command: |
+            echo 'export CCI_STATUS="${CIRCLE_JOB}"' >> $BASH_ENV
+            source $BASH_ENV
 
-#     - slack/notify:
-#         event: fail
-#         channel: ${SLACK_CHANNEL_ID}
-#         custom: |
-#           {
-#             "blocks": [
-#               {
-#                 "type": "section",
-#                 "fields": [
-#                   {
-#                     "type": "plain_text",
-#                     "text": "Job: ${CIRCLE_JOB}",
-#                     "emoji": true
-#                   },
-#                   {
-#                     "type": "plain_text",
-#                     "text": "Status: Fail",
-#                     "emoji": true
-#                   }
-#                 ]
-#               }
-#             ]
-#           }
+      - slack/notify:
+          event: fail
+          channel: ${SLACK_CHANNEL_ID_BUILD}
+          template: basic_fail_1
 
-#     - slack/notify:
-#         event: pass
-#         channel: ${SLACK_CHANNEL_ID}
-#         custom: |
-#           {
-#             "blocks": [
-#               {
-#                 "type": "section",
-#                 "fields": [
-#                   {
-#                     "type": "plain_text",
-#                     "text": "Job: ${CIRCLE_JOB}",
-#                     "emoji": true
-#                   },
-#                   {
-#                     "type": "plain_text",
-#                     "text": "Status: Pass",
-#                     "emoji": true
-#                   }
-#                 ]
-#               }
-#             ]
-#           }
+      - slack/notify:
+          event: pass
+          channel: ${SLACK_CHANNEL_ID_BUILD}
+          template: basic_success_1
 
-# deploy-to-ecs:
-#   docker:
-#     - image: cimg/base:stable
-#   steps:
-#     - aws-cli/setup
-#     - run:
-#         name: Deploy to ECS
-#         command: |
-#           TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition ofcrm-app --query 'taskDefinition.taskDefinitionArn' --output text)
-#           aws ecs update-service --cluster ofcrm-cluster --service ofcrm-service --task-definition $TASK_DEFINITION --force-new-deployment
+  deploy-to-ecs:
+    docker:
+      - image: cimg/base:stable
+    steps:
+      - aws-cli/setup
+      - run:
+          name: Deploy to ECS
+          command: |
+            TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition ofcrm-app --query 'taskDefinition.taskDefinitionArn' --output text)
+            aws ecs update-service --cluster ofcrm-cluster --service ofcrm-service --task-definition $TASK_DEFINITION --force-new-deployment
 
-#     - run:
-#         name: Wait for service to be stable
-#         command: |
-#           aws ecs wait services-stable --cluster ofcrm-cluster --services ofcrm-service
+      - run:
+          name: Wait for service to be stable
+          command: |
+            aws ecs wait services-stable --cluster ofcrm-cluster --services ofcrm-service
 
-#     - run:
-#         name: Verify deployment
-#         command: |
-#           HEALTH_CHECK_URL="https://api.tkb-tech.com/health"
-#           HEALTH_CHECK_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" $HEALTH_CHECK_URL)
-#           if [ "$HEALTH_CHECK_RESPONSE" = "200" ]; then
-#             echo "Deployment successful. Health check passed."
-#           else
-#             echo "Deployment may have failed. Health check returned status $HEALTH_CHECK_RESPONSE"
-#             exit 1
-#           fi
+      - run:
+          name: Verify deployment
+          command: |
+            HEALTH_CHECK_URL="https://api.tkb-tech.com/health"
+            HEALTH_CHECK_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" $HEALTH_CHECK_URL)
+            if [ "$HEALTH_CHECK_RESPONSE" = "200" ]; then
+              echo "Deployment successful. Health check passed."
+            else
+              echo "Deployment may have failed. Health check returned status $HEALTH_CHECK_RESPONSE"
+              exit 1
+            fi
 
-#     - run:
-#         name: Set job status
-#         command: |
-#           echo 'export CCI_STATUS="${CIRCLE_JOB}"' >> $BASH_ENV
-#           source $BASH_ENV
+      - run:
+          name: Set job status
+          command: |
+            echo 'export CCI_STATUS="${CIRCLE_JOB}"' >> $BASH_ENV
+            source $BASH_ENV
 
-#     - slack/notify:
-#         event: fail
-#         channel: ${SLACK_CHANNEL_ID}
-#         custom: |
-#           {
-#             "blocks": [
-#               {
-#                 "type": "section",
-#                 "fields": [
-#                   {
-#                     "type": "plain_text",
-#                     "text": "Job: ${CIRCLE_JOB}",
-#                     "emoji": true
-#                   },
-#                   {
-#                     "type": "plain_text",
-#                     "text": "Status: Fail",
-#                     "emoji": true
-#                   }
-#                 ]
-#               }
-#             ]
-#           }
+      - slack/notify:
+          event: fail
+          channel: ${SLACK_CHANNEL_ID_DEPLOY}
+          template: basic_fail_1
 
-#     - slack/notify:
-#         event: pass
-#         channel: ${SLACK_CHANNEL_ID}
-#         custom: |
-#           {
-#             "blocks": [
-#               {
-#                 "type": "section",
-#                 "fields": [
-#                   {
-#                     "type": "plain_text",
-#                     "text": "Job: ${CIRCLE_JOB}",
-#                     "emoji": true
-#                   },
-#                   {
-#                     "type": "plain_text",
-#                     "text": "Status: Pass",
-#                     "emoji": true
-#                   }
-#                 ]
-#               }
-#             ]
-#           }
+      - slack/notify:
+          event: pass
+          channel: ${SLACK_CHANNEL_ID_DEPLOY}
+          template: basic_success_1
 
 workflows:
   version: 2
@@ -515,17 +439,17 @@ workflows:
     jobs:
       - build-and-test:
           context: my-context
-      # - build-and-push-image:
-      #     context: my-production-context
-      #     requires:
-      #       - build-and-test
-      #     filters:
-      #       branches:
-      #         only: main
-      # - deploy-to-ecs:
-      #     context: my-production-context
-      #     requires:
-      #       - build-and-push-image
-      #     filters:
-      #       branches:
-      #         only: main
+      - build-and-push-image:
+          context: my-production-context
+          requires:
+            - build-and-test
+          filters:
+            branches:
+              only: main
+      - deploy-to-ecs:
+          context: my-production-context
+          requires:
+            - build-and-push-image
+          filters:
+            branches:
+              only: main
