API: broadcasting.phpの修正

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,9 +2,13 @@ version: 2.1
 
 orbs:
   node: circleci/node@5.0.2
+  slack: circleci/slack@4.1.0
+  aws-ecr: circleci/aws-ecr@6.15.3
+  aws-ecs: circleci/aws-ecs@2.1.0
+  aws-cli: circleci/aws-cli@2.0.3
 
 jobs:
-  build:
+  build-and-test:
     machine:
       image: ubuntu-2204:current
 
@@ -129,7 +133,6 @@ jobs:
             if [ "$SKIP_API_TESTS" = "false" ]; then
               cd ~/project/api/src
               composer install --no-interaction --prefer-dist
-              composer install --no-interaction --prefer-dist
             fi
 
       - save_cache:
@@ -230,9 +233,142 @@ jobs:
               npm test
             fi
 
+      - slack/notify:
+          event: fail
+          channel: ${SLACK_CHANNEL_ID}
+          template: basic_fail_1
+
+      - slack/notify:
+          event: pass
+          channel: ${SLACK_CHANNEL_ID}
+          template: success_tagged_deploy_1
+
+  build-and-push-image:
+    docker:
+      - image: cimg/base:stable
+    steps:
+      - checkout
+      - run:
+          name: Checkout submodules
+          command: |
+            git submodule sync
+            git submodule update --init --recursive
+      - setup_remote_docker
+      - aws-cli/setup
+      - run:
+          name: Get RDS endpoint and prepare .env.production
+          command: |
+            # RDSエンドポイントの取得
+            DB_HOST=$(aws rds describe-db-instances --db-instance-identifier ofcrm-mysql --query "DBInstances[0].Endpoint.Address" --output text)
+
+            # .env.productionファイルの生成
+            cd ./api/src
+            echo "APP_NAME=OFCRM" > .env.production
+            echo "APP_ENV=production" >> .env.production
+            echo "APP_KEY=${APP_KEY}" >> .env.production
+            echo "APP_DEBUG=false" >> .env.production
+            echo "APP_URL=https://api.tkb-tech.com" >> .env.production
+
+            echo "DB_CONNECTION=mysql" >> .env.production
+            echo "DB_HOST=${DB_HOST}" >> .env.production
+            echo "DB_PORT=3306" >> .env.production
+            echo "DB_DATABASE=flowercrm_production" >> .env.production
+            echo "DB_USERNAME=${DB_USERNAME}" >> .env.production
+            echo "DB_PASSWORD=${DB_PASSWORD}" >> .env.production
+
+            echo "BROADCAST_DRIVER=log" >> .env.production
+            echo "PUSHER_APP_ID=null" >> .env.production
+            echo "PUSHER_APP_KEY=null" >> .env.production
+            echo "PUSHER_APP_SECRET=null" >> .env.production
+            echo "PUSHER_HOST=null" >> .env.production
+            echo "PUSHER_PORT=null" >> .env.production
+            echo "PUSHER_SCHEME=https" >> .env.production
+            echo "PUSHER_APP_CLUSTER=null" >> .env.production
+
+            echo "JWT_SECRET=${JWT_SECRET}" >> .env.production
+            echo "JWT_ALGO=${JWT_ALGO}" >> .env.production
+
+            echo "FRONTEND_URL=https://front.tkb-tech.com" >> .env.production
+      - run:
+          name: Set ECR URL and Build Docker Image
+          command: |
+            echo "Setting ECR URL..."
+            echo "export ECR_ENDPOINT=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com" >> $BASH_ENV
+            source $BASH_ENV
+            echo "ECR Endpoint: $ECR_ENDPOINT"
+
+            echo "Logging in to AWS ECR..."
+            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_ENDPOINT
+
+            echo "Building Docker image..."
+            docker build \
+              --build-arg NGINX_CONF_PATH=./infra/nginx/nginx.prod.conf \
+              --build-arg DEFAULT_CONF_PATH=./infra/nginx/default.prod.conf \
+              --build-arg PHP_INI_PATH=./infra/php/php.prod.ini \
+              --build-arg ENTRYPOINT_SCRIPT_PATH=./infra/php/docker-entrypoint.prod.sh \
+              -t $ECR_ENDPOINT/ofcrm-app:${CIRCLE_SHA1} \
+              -f ./api/infra/php/Dockerfile.prod \
+              ./api
+
+            if [ $? -ne 0 ]; then
+              echo "Docker build failed"
+              exit 1
+            fi
+
+            echo "Docker build successful. Listing images:"
+            docker images
+
+            echo "Pushing image to ECR..."
+            docker push $ECR_ENDPOINT/ofcrm-app:${CIRCLE_SHA1}
+
+            if [ $? -ne 0 ]; then
+              echo "Failed to push image to ECR"
+              exit 1
+            fi
+
+            echo "Image successfully pushed to ECR"
+
+            echo "Describing image in ECR..."
+            aws ecr describe-images --repository-name ofcrm-app --image-ids imageTag=${CIRCLE_SHA1}
+      - slack/notify:
+          event: fail
+          channel: ${SLACK_CHANNEL_ID}
+          template: basic_fail_1
+      - slack/notify:
+          event: pass
+          channel: ${SLACK_CHANNEL_ID}
+          template: success_tagged_deploy_1
+
 workflows:
   version: 2
-  build_and_test:
+  build-test-deploy:
     jobs:
-      - build:
+      - build-and-test:
           context: my-context
+      - build-and-push-image:
+          context: my-context
+          requires:
+            - build-and-test
+          filters:
+            branches:
+              only: main
+      - aws-ecs/deploy-service-update:
+          context: my-context
+          requires:
+            - build-and-push-image
+          family: ofcrm-app
+          cluster-name: ofcrm-cluster
+          service-name: ofcrm-service
+          container-image-name-updates: "ofcrm-app=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/ofcrm-app:${CIRCLE_SHA1}"
+          post-steps:
+            - slack/notify:
+                event: fail
+                channel: ${SLACK_CHANNEL_ID}
+                template: basic_fail_1
+            - slack/notify:
+                event: pass
+                channel: ${SLACK_CHANNEL_ID}
+                template: success_tagged_deploy_1
+          filters:
+            branches:
+              only: main
